---

- hosts: tag_Ansible
  gather_facts: True
  become: yes

  vars:
    source_file: ./index.html
    dest_file: /var/www/html
    ansible_user: ec2-user 
    ansible_ssh_private_key_file: ../Terraform/Dev/Webserver/projectkey

  tasks:
    - name: ping
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true

    - name: Install Apache Web Server
      yum: name=httpd state=latest
      
    - name: Start Apache Web Server
      service: name=httpd state=started enabled=yes

    - name: Copy index.html
      copy: src={{ source_file }} dest={{ dest_file }} mode=0555

    - name: Replace $myip with server's IP
      ansible.builtin.replace:
        path: "{{ dest_file }}/index.html"
        regexp: '\$myip'
        replace: "{{ ansible_default_ipv4.address }}"
    